# Relevant Packages

In [219]:
import numpy as np
import math

# Initializing Variables

In [220]:
#
# Option Parameters
#

'''
S_0 = Initial Stock Price
K = Strike
T = Time to Maturity
r = Risk-Free Rate
vol = Volatility
'''

S_0 = 105 
K = 100
T = 1
r = 0.05
vol = 0.25

In [221]:
#
# Time Parameters
#

'''
M = Time Steps
dt = Length of Each Time Step
df = discount factor
'''

M = 3
dt = T/M
df = math.exp(-r*dt)

In [222]:
#
# Binomial Tree Parameters
#

'''
u = up factor
d = down factor
p = probability of up move
'''

u = math.exp(vol*math.sqrt(dt))
d = 1/u
p = (math.exp(r*dt) - d) / (u - d)

# Constructing the Tree

In [229]:
#
# Create an array with relevant indexing
#

mu = np.arange(M+1)
mu = np.resize(mu, (M+1, M+1))
md = np.transpose(mu)
mu = np.triu(mu)
md = np.triu(md)

In [230]:
mu

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 0, 2, 3],
       [0, 0, 0, 3]])

In [231]:
md #Number of down movements

array([[0, 0, 0, 0],
       [0, 1, 1, 1],
       [0, 0, 2, 2],
       [0, 0, 0, 3]])

In [232]:
mu - md #Number of up movements

array([[0, 1, 2, 3],
       [0, 0, 1, 2],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [233]:
mu = u ** (mu - md)
md = d ** md
S = S_0 * mu * md 
S = np.triu(S)
S

array([[105.        , 121.30377267, 140.13909775, 161.89905958],
       [  0.        ,  90.88752771, 105.        , 121.30377267],
       [  0.        ,   0.        ,  78.67183517,  90.88752771],
       [  0.        ,   0.        ,   0.        ,  68.09798666]])

# Risk-Neutral Discounting

In [234]:
pv = np.maximum(S - K, 0)
z = 0
for i in range(M - 1, -1, -1):
    pv[0:M - z, i] = (p * pv[0:M - z, i + 1] + (1 - p) * pv[1:M - z + 1, i + 1]) * df
    z += 1
    
print("Value of European call option is %8.3f" % pv[0, 0])

Value of European call option is   16.293
